### ISSUE TITLE
Missing development dependencies

### ISSUE THREAD

**Issue by mnaki** [KleineEdelweiss/lmsensors_rb#1]
The README.md file should tell the user which dependencies are required in order to install the gem file.

I suggest these for Ubuntu since it's the main development OS for many of us :

`libsensors-dev`

`ruby-dev`

What do you think?

**Comment by KleineEdelweiss** [comment]
Ah yeah, good point. I did actually include ``libsensors-dev``, but I will add ``ruby-dev``
